#!/usr/bin/env bash
# -------------------------------------------------------------------
# Source this script to set up ephemeral Terraform credentials for the
# Sequoia Fabrica authentik workspace.
#
#   1. SSHes to the nursery host and mints a 1-hour API token for your
#      authentik user via `ak shell` (no long-lived tokens anywhere).
#   2. Queries the API for the objects this workspace manages and writes
#      imports.generated.tf (gitignored) so a fresh `terraform plan` adopts
#      what already exists instead of trying to re-create it. There is no
#      persistent .tfstate; every session starts from scratch.
#
# Usage:
#   source setup-env.sh [authentik-username]
#
# The argument is your *authentik* username, defaulting to $(whoami). You
# need SSH access to nursery (Tailscale) and superuser rights in authentik.
# -------------------------------------------------------------------

set -euo pipefail

AUTHENTIK_HOST="login.sequoia.garden"
AUTHENTIK_SSH_HOST="nursery.cloudforest-perch.ts.net"
AUTHENTIK_CONTAINER="authentik-server-1"
AK_USER="${1:-$(whoami)}"
TOKEN_ID="terraform-$(date +%s)"
_here="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"

echo "==> Creating ephemeral API token for user '${AK_USER}' via ${AUTHENTIK_SSH_HOST}..."
_ak_err=$(mktemp)
AUTHENTIK_TOKEN=$(ssh "${AUTHENTIK_SSH_HOST}" \
  "sudo docker exec ${AUTHENTIK_CONTAINER} ak shell -c \"
from authentik.core.models import Token, TokenIntents, User
from django.utils import timezone
from datetime import timedelta
u = User.objects.get(username='${AK_USER}')
t = Token.objects.create(
    identifier='${TOKEN_ID}',
    user=u,
    intent=TokenIntents.INTENT_API,
    expiring=True,
    expires=timezone.now() + timedelta(hours=1),
    description='Ephemeral Terraform token',
)
print(t.key)
\"" 2>"${_ak_err}" | tail -1) || true

if [[ -z "${AUTHENTIK_TOKEN}" ]]; then
  echo "ERROR: Failed to create API token for authentik user '${AK_USER}'." >&2
  if grep -q "User matching query does not exist" "${_ak_err}"; then
    echo "       No authentik user named '${AK_USER}'. Pass it explicitly:" >&2
    echo "         source setup-env.sh <authentik-username>" >&2
  else
    echo "       Remote error (last lines):" >&2
    grep -vE '"logger": "authentik' "${_ak_err}" | tail -5 | sed 's/^/         /' >&2
  fi
  rm -f "${_ak_err}"
  return 1 2>/dev/null || exit 1
fi
rm -f "${_ak_err}"

export AUTHENTIK_URL="https://${AUTHENTIK_HOST}/"
export AUTHENTIK_TOKEN

echo "==> Discovering existing objects and writing imports.generated.tf..."
python3 - "${AUTHENTIK_URL}" "${AUTHENTIK_TOKEN}" "${AUTHENTIK_HOST}" "${_here}/imports.generated.tf" <<'PY'
import json, sys, urllib.parse, urllib.request

base, token, domain, out_path = sys.argv[1:5]

def get(path, **params):
    url = f"{base}api/v3/{path}?{urllib.parse.urlencode(params)}" if params else f"{base}api/v3/{path}"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

blocks = []
def imp(to, ident):
    blocks.append(f'import {{\n  to = {to}\n  id = "{ident}"\n}}\n')

# Brand: match on domain; fall back to the default brand.
brands = get("core/brands/").get("results", [])
brand = next((b for b in brands if b["domain"] == domain), None) or next((b for b in brands if b["default"]), None)
if not brand:
    sys.exit(f"no brand found for {domain} and no default brand exists")
imp("authentik_brand.sequoia_fabrica", brand["brand_uuid"])
print(f"    brand      {brand['brand_uuid']}  domain={brand['domain']} title={brand['branding_title']!r}")

# Branded flow + its stage bindings: only present after the first apply.
flow_slug = "sequoia-fabrica-authentication"
flows = get("flows/instances/", slug=flow_slug).get("results", [])
if flows:
    flow = flows[0]
    imp("authentik_flow.sequoia_fabrica_authentication", flow_slug)
    print(f"    flow       {flow['pk']}  slug={flow_slug}")
    bindings = get("flows/bindings/", target=flow["pk"], ordering="order").get("results", [])
    names = {
        "default-authentication-identification": "sequoia_fabrica_auth_identification",
        "default-authentication-mfa-validation": "sequoia_fabrica_auth_mfa_validation",
        "default-authentication-login": "sequoia_fabrica_auth_login",
    }
    for b in bindings:
        res = names.get(b["stage_obj"]["name"])
        if res:
            imp(f"authentik_flow_stage_binding.{res}", b["pk"])
            print(f"    binding    {b['pk']}  order={b['order']} stage={b['stage_obj']['name']}")
        else:
            print(f"    WARNING: unmanaged binding {b['pk']} (stage {b['stage_obj']['name']}) on {flow_slug}")
else:
    print(f"    flow       (not created yet: {flow_slug}; first apply will create it)")

header = (
    "# GENERATED by setup-env.sh -- do not edit, do not commit.\n"
    "# Maps objects that already exist on the instance to Terraform addresses.\n\n"
)
with open(out_path, "w") as f:
    f.write(header + "\n".join(blocks))

# Inventory of things this workspace does *not* manage yet, for reference.
apps = get("core/applications/").get("results", [])
if apps:
    print("    (unmanaged) applications:", ", ".join(f"{a['slug']}" for a in apps))
PY

echo "==> Ready. Token: ${TOKEN_ID} (user: ${AK_USER}, expires in 1h)"
echo "    AUTHENTIK_URL=${AUTHENTIK_URL}"
echo "    Run: terraform init && terraform plan"
