## This file is managed by Ansible in the repo github.com/Sequoia-Fabrica/infrastructure
## Send edits there, as local changes here may be replaced by an Ansible run

mqtt:
  enabled: true
  host: 192.168.88.254
  port: 1883
  user: mqtt
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  coral_usb:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    front_door:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.100:554/cam/realmonitor?channel=1&subtype=0
    side_door:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.101:554/cam/realmonitor?channel=1&subtype=0
    # workshop:
    #   - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.102:554/cam/realmonitor?channel=1&subtype=0
    fablab:
      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.103:554/cam/realmonitor?channel=1&subtype=0


record:
  enabled: true
  expire_interval: 180
  retain:
    days: 2
    mode: motion
  alerts:
    retain: {}
    pre_capture: 5
    post_capture: 5
  detections:
    retain: {}
    pre_capture: 5
    post_capture: 5
cameras:
  front_door:
    enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.100:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.100:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
    motion:
      mask: 0.135,0.258,0.138,0.316,0.215,0.293,0.207,0.248
  side_door:
    enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.101:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
    motion:
      mask: 0.445,0.339,0.442,0.45,0.585,0.47,0.584,0.377
  workshop:
    enabled: false
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.102:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.102:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
  fablab:
    enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.103:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.44.103:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true
    record:
      enabled: true
    motion:
      mask: 
        0.595,0.5,0.588,0.668,0.836,0.74,0.85,0.548,0.73,0.52,0.711,0.435,0.616,0.412
