---
- name: Add the Cloudflare APT Key
  become: true
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
- name: Add the cloudflare APT repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release }} main"
    filename: cloudflared
    state: present
- name: Install cloudflared
  become: true
  ansible.builtin.apt:
    name: cloudflared
    state: latest
    update_cache: true
- name: Check for an existing cloudflared systemd service
  become: true
  ansible.builtin.systemd_service:
    name: cloudflared
  register: cloudflared_systemd_exists
- name: Register cloudflared service if it doesn't exist
  become: true
  when: cloudflared_systemd_exists.status.LoadState == "not-found"
  ansible.builtin.command:
    cmd: "cloudflared service install {{ cloudflared.tunnel_token }}"
- name: Start cloudflared
  become: true
  ansible.builtin.systemd_service:
    name: cloudflared
    state: started
    enabled: true
    masked: false
