---
- name: "Admin users: Ensure Github SSH keys directory"
  delegate_to: localhost
  ansible.builtin.file:
    dest: "{{ (playbook_dir ~ '/.github_ssh_keys/') }}"
    state: directory
    mode: ug=rwx,o=rx

- name: "Admin users: Download keys from Github"
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "https://github.com/{{ item.github_username }}.keys"
    dest: "{{ (playbook_dir ~ '/.github_ssh_keys/' ~ item.github_username ~ '.keys') }}"
    mode: ugo=rw
  with_items: "{{ sequoia_fabrica_users }}"
