---
## Multipass - Digital Makerspace ID System
- name: Create multipass data directory
  become: true
  ansible.builtin.file:
    path: "{{ multipass.data_location }}"
    state: directory
    owner: root
    group: root
    mode: ug=rwx,o=rx
- name: Create multipass config directory
  become: true
  ansible.builtin.file:
    path: "{{ multipass.data_location }}/config"
    state: directory
    owner: root
    group: root
    mode: ug=rwx,o=rx
- name: Template multipass group mapping config
  become: true
  ansible.builtin.template:
    src: multipass.group_mapping.yaml.j2
    dest: "{{ multipass.data_location }}/config/group_mapping.yaml"
    owner: root
    group: root
    mode: ug=rw,o=r
- name: Run multipass
  become: true
  community.docker.docker_container:
    name: multipass
    image: ghcr.io/sequoia-fabrica/infrastructure/multipass:{{ multipass.container_version }}
    pull: always
    restart_policy: unless-stopped
    ports:
      - "{{ multipass.port }}:3000"
    env:
      ENVIRONMENT: "{{ multipass.environment }}"
      AUTHENTIK_URL: "{{ multipass.authentik_url }}"
      AUTHENTIK_API_TOKEN: "{{ multipass.authentik_api_token }}"
      BIND_ADDRESS: "0.0.0.0"
      PORT: "3000"
      MAKERSPACE_NAME: "{{ multipass.makerspace_name }}"
      MAKERSPACE_LOGO_URL: "/static/images/logo.png"
      TRUSTED_PROXY_HEADERS: "{{ multipass.trusted_proxy_headers | string | lower }}"
      GROUP_MAPPING_CONFIG: "/config/group_mapping.yaml"
      TOKEN_SECRET: "{{ multipass.multipass_token_secret }}"
    mounts:
      - type: bind
        source: "{{ multipass.data_location }}/config"
        target: /config
        read_only: true
