---
- name: Restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload prometheus
  become: true
  ansible.builtin.command: docker kill --signal=SIGHUP prometheus
  changed_when: true

- name: Restart aruba_exporter
  community.docker.docker_container:
    name: aruba_exporter
    restart: true
    recreate: true

- name: Restart frigate
  community.docker.docker_container:
    name: frigate
    restart: true
  ignore_errors: true

- name: Restart cloudflared
  become: true
  ansible.builtin.systemd_service:
    name: cloudflared.service
    state: restarted

- name: Restart double-take
  community.docker.docker_container:
    name: double-take
    restart: true
  ignore_errors: true
