---
- name: Restart docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reload prometheus
  become: true
  command: docker kill --signal=SIGHUP prometheus
  changed_when: true

- name: Restart aruba_exporter
  community.docker.docker_container:
    name: aruba_exporter
    restart: yes
    recreate: yes

- name: Restart frigate
  community.docker.docker_container:
    name: frigate
    restart: yes
  ignore_errors: true
